### ISSUE TITLE
Add option to change dependency direction between an Interface an the implementing classes

### ISSUE THREAD

**Issue by BenjaminWeisheit** [Moose2Model/Moose2Model#100]
Hello Rainer,

Currently the dependency arrow between an interface and a class that implements the interface always points from the interface towards the class. It would be really helpful to have an option that allows to switch this direction. So that a class points towards the interfaces it implements

At the same time a class that calls the methods/attributes defined in an interface should should also point toward the interface.

Example:
Implementing Class--->Implemented Interface<-----Client Class

Best regards,
Ben

**Comment by BenjaminWeisheit** [comment]
Sorry, wrong repository

**Comment by RainerWinkler** [comment]
Hello @BenjaminWeisheit ,
I contact you because the Moose2Model version in Smalltalk is currently replaced by a new version in Javascript. See this repository https://github.com/Moose2Model/Moose2Model2 .
The feature you requested with this ticket is currently not implemented there. It is also not part of the new metamodel SOMIX which I use now.
Please open a ticket in the new project when you need this feature also there.
You may see also my recent blog at sap.com where I explain the basics of the new implementation (https://blogs.sap.com/2022/08/28/somix-suite-for-software-visualization/).
Best regards,
Rainer

**Comment by BenjaminWeisheit** [comment]
Hello Rainer,

thank you very much for the update.

Meanwhile we moved to a commercial solution for ABAP Code visualization. It is integrated into Eclipse and allows us to compare the actual and our target architecture and show violations directly in the IDE.

Nevertheless I’ll check out Moose2Model with SOMIX.

Thank you very much and best regards,
Ben

Von: Benjamin Weisheit ***@***.******@***.***>>
Gesendet: Samstag, 10. September 2022 06:42
An: Weisheit Benjamin ***@***.******@***.***>>
Betreff: Fwd: [Moose2Model/Moose2Model] Add option to change dependency direction between an Interface an the implementing classes (#100)




Anfang der weitergeleiteten Nachricht:
Von: Rainer Winkler ***@***.******@***.***>>
Datum: 9. September 2022 um 22:06:51 MESZ
An: Moose2Model/Moose2Model ***@***.******@***.***>>
Kopie: Benjamin Weisheit ***@***.******@***.***>>, Mention ***@***.******@***.***>>
Betreff: Aw: [Moose2Model/Moose2Model] Add option to change dependency direction between an Interface an the implementing classes (#100)
Antwort an: Moose2Model/Moose2Model ***@***.******@***.***>>
﻿

Hello @BenjaminWeisheit<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBenjaminWeisheit&data=05%7C01%7Cb.weisheit%40netze-bw.de%7C9e49256ec0914ea1f31208da92e6c0b1%7Cee920d5446e44e1eaa996d010a689325%7C0%7C0%7C637983817012592641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nRGzKmE8pJM75bSUMnWvIukTRNADpwvZWuryzs9aYNk%3D&reserved=0> ,
I contact you because the Moose2Model version in Smalltalk is currently replaced by a new version in Javascript. See this repository https://github.com/Moose2Model/Moose2Model2<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMoose2Model%2FMoose2Model2&data=05%7C01%7Cb.weisheit%40netze-bw.de%7C9e49256ec0914ea1f31208da92e6c0b1%7Cee920d5446e44e1eaa996d010a689325%7C0%7C0%7C637983817012592641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p7z2xykKyoOeRwlPYJJORgArt9hC5o7EgjFxPu%2F4o5M%3D&reserved=0> .
The feature you requested with this ticket is currently not implemented there. It is also not part of the new metamodel SOMIX which I use now.
Please open a ticket in the new project when you need this feature also there.
You may see also my recent blog at sap.com where I explain the basics of the new implementation (https://blogs.sap.com/2022/08/28/somix-suite-for-software-visualization/<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.sap.com%2F2022%2F08%2F28%2Fsomix-suite-for-software-visualization%2F&data=05%7C01%7Cb.weisheit%40netze-bw.de%7C9e49256ec0914ea1f31208da92e6c0b1%7Cee920d5446e44e1eaa996d010a689325%7C0%7C0%7C637983817012748443%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F6wYF2fK9UlnrmYbvrXFcwlZRvkE1askTfXEu1Vy3%2Fs%3D&reserved=0>).
Best regards,
Rainer

**Comment by RainerWinkler** [comment]
Hello Ben,

thank you for the feedback. It is good that you found a commercial solution which works for you. Please contact me when you have any questions or ideas.

Best regards,
Rainer
