### ISSUE TITLE
Display accesses to attributes as blue arrows

### ISSUE THREAD

**Issue by BenjaminWeisheit** [Moose2Model/Moose2Model#102]
Hi @RainerWinkler,

I have a feature request. Would it possible to display accesses to attributes as blue arrows, instead of blue lines? This would be helpful to check if dependency inversion has been respected not only for classes but also for attributes.

Thank you and best regards,
Ben

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit ,

it should be possible to create blue arrows for accesses to attributes. But as this will be done in Moose2Model, there will be no "dependency inversion" (You speak of issue 131 of the SAP2Moose repository [Add option to change dependency direction between an Interface an the implementing classes #131](https://github.com/SAP2Moose/SAP2Moose/issues/131)  ?).

What I can implement now is that blue arrows point always from a method to an accessed attribute. Is it this what you need?

Kind regards,
Rainer
PS: I am currently working on a more flexible metamodel than the metamodel that is currently used by SAP2Moose and displayed by Moose2Model. For the current metamodel see this paper: [Circuit Diagram for Software - Reverse-engineered customizable, complete, and abstract visualization of dependencies which preserve the mental map for SAP applications](https://www.doi.org/10.13140/RG.2.2.13306.41927)

**Comment by BenjaminWeisheit** [comment]
Hi @RainerWinkler,

having arrows that point from a method to an accessed attribute, would help me to check that lower level packages always depend on higher level packages. 

E.g. there is a lower level package which deals with the data model and a higher level package that contains business logic. The Business logic should not depend directly on the data model. Instead the data model implements an interface of the business logic (its "plugged in") or alternatively there could be an adapter class in between.

So there should be no arrow pointing from the business logic Package toward the data model and this applies also for attributes. With a blue arrow instead on a line, this would be easy to spot on package level.

Best regards,
Ben

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit ,
thank you. I will have a look on this. I assume you need it to work correctly also when only packages or classes are displayed.
Best regards,
Rainer

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit ,
you can test now.
To test you have to get the development version.
(Paste this into the playground:
Metacello new 
    repository: 'http://ss3.gemstone.com/ss/Moose2Model';
    configuration: 'Moose2Model';
    version: #development;
    get;
    load.
)
You can do this in an existing image. But you have to generate the diagram new, otherwise you will not see it.
You find in the context menu of the background of an image the new point:
"Toggle Access with Arrows (Point to attribute)"

You may have to drag the background a bit, so that the image refreshes. This takes typically a few seconds, depending on the size of the model.

This correction is contained in release 1.4.1.

**Comment by BenjaminWeisheit** [comment]
Hello Rainer,

thank you very much. Your change seems to work quite well.

This completes the picture and I already found some violations of the dependencies in my project.

I'm closing this request.

Thanks again and best regards,
Ben

**Comment by RainerWinkler** [comment]
Hello Ben,

thank you for testing and best regards,

Rainer
