### ISSUE TITLE
Display Dependencies of Classes, Interfaces and Packages

### ISSUE THREAD

**Issue by stefannothaft** [Moose2Model/Moose2Model#22]
Every method and attribute would be considered as one dependency, right? Is it somehow possible to “aggregate” them? So, in the first place I’m not interested in which method/attribute is used by which method, but I would like to investigate the dependencies between classes/interfaces – like the big ball of mud…
Maybe, in the ABAP environment (SAP2Moose), the extraction process could work accordingly?

**Comment by RainerWinkler** [comment]
I would not solve this in the ABAP environment (SAP2Moose), even though it is possible.
I prefer to refactor RWDiagram>>methodUsage:withEditor:test: and add additional layers to separate the displayed diagram from the internal model.

**Comment by RainerWinkler** [comment]
Main implementation is finished. The logic is now in developer test.

**Comment by RainerWinkler** [comment]
The issue is solved with release v0.4.0.
The new statements to set the scope are available to be executed in the Playground:
RWDiagram setMethodScope.
RWDiagram setClassScope.
RWDiagram setPackageScope.
The scope is also saved and read from file.
