### ISSUE TITLE
Broken Link for Windows Image download

### ISSUE THREAD

**Issue by mrbandler** [Moose2Model/Moose2Model#42]
When I try to download the image in the [wiki/installation](https://github.com/Moose2Model/Moose2Model/wiki/Installation) I get a network error.

![image](https://user-images.githubusercontent.com/7815115/33428666-ff2d8de4-d5c9-11e7-80f8-2d2f47051e79.png)

**Comment by RainerWinkler** [comment]
Hi @mrbandler 
sorry for my late reply, I somehow missed to see your ticket.
I will check this.
Rainer

**Comment by RainerWinkler** [comment]
I am able to download from http://www.poaceae.de/RWDiagram/Images/Windows/Moose2Model_v0.4.5.zip using the Chrome browser.
So the link itself should exist. There may be a problem due to the file size (90MB).

**Comment by RainerWinkler** [comment]
I found now the notification Email in my trash folder, sorry.

**Comment by RainerWinkler** [comment]
@mrbandler I downloaded the file now with curl on Ubuntu Linux with the -o filename option. Can you try it again?
I also see no specification of a file name in your example, in Linux the output is then to the standard output, which is the terminal. But you are using probably Powershell, or? So it may be different there.

**Comment by mrbandler** [comment]
Sorry for the late response. I tested the link again in a different network environment, and it works there.
It was a firewall issue on my end.

I think we can close the issue, sorry for the inconvenience and thanks for the quick response.

**Comment by RainerWinkler** [comment]
I am happy to hear this. Please make sure that you use release 1.0.0 or higher. I made a lot of improvements to make the tool much easier to be use in the last weeks. 
Thank you very much,
Rainer
