### ISSUE TITLE
 support for JavaScript

### ISSUE THREAD

**Issue by scrumit** [Moose2Model/Moose2Model#96]
hi, just started investigating old and complicated codebase. 

as suggested and so you know some people are interested, I am looking at an open source tool, Joplin, that has a lot of issues around encryption keys and synchronisation,

it is written using React.

**Comment by RainerWinkler** [comment]
Hi Mel,
what tool do you plan to derive an mse file from JavaScript? Moose2Model depends currently heavily on the kind of mse that is provided. Indead SAP2Moose extracts nearto everything into Package, Class, Method and Attribute. The interpretation is: Package = Grouping 1, Class = Grouping 2, Method = Code, Attribute = Information that is stored.
BR
Rainer

**Comment by RainerWinkler** [comment]
Hi @scrumit is this ticket still open?
Kind Regards,
Rainer

**Comment by RainerWinkler** [comment]
Closed as user did not reply on request to explain his requirement

**Comment by scrumit** [comment]
sorry, too much (open source) software was failing on the arm based macs. I don't think I'm in a position to work on that part; [this article about creating mse from java/c#](https://erik.doernenburg.com/2009/07/moose-mse-for-java-and-cs/) has broken links to the MSE format.
