### ISSUE TITLE
Dpendencys point from Interfaces to implementing classes

### ISSUE THREAD

**Issue by BenjaminWeisheit** [Moose2Model/Moose2Model#99]
Hello Rainer,

I'm currently discovering Moose2Model and the ABAP extractor and would like to thank you for your great work. There's something about the diagram that seem's a little unusual to me. It looks like the dependency arrow between an interface and a class that implements the interface always point from the interface towards the class. Is that intended?

I would have expected the opposite since a class knows about the interface it implements. Not the other way round.

I like to keep interfaces in higher level packages and the classes/components that realize these Interfaces in lower level packages, so I can "plug" these lower level components into the higher level components. So having interfaces that point towards classes turns the dependencies upside down. 

Best regards,
Ben

<img width="142" alt="dependency" src="https://user-images.githubusercontent.com/77887261/105580490-fc062d80-5d8c-11eb-869b-1971cbb2a217.png">

**Comment by RainerWinkler** [comment]
Hello Benjamin,

sorry for the late reply.

The direction of the arrow is intended. The idea is that an arrow points from a method to a method it calls. In case Method A calls Method C via an Interface Method B, the arrows should point from A to B and from B to C. The Where-used logic from ABAP implemented this in the other direction. I reversed the arrow for Interfaces there explicitly in SAP2Moose. 

This was implemented in SAP2Moose with issue 33 https://github.com/SAP2Moose/SAP2Moose/issues/33.

When you need the arror in the other direction, we can open a new issue in SAP2Moose to provide this as an option.

Best regards,
Rainer

PS: The direction of the arrows is specified in a "metamodel of abstract element types" which is partly used by SAP2Moose and Moose2Model (A paper on this exists, but I work currently for the preprint to be available).

**Comment by BenjaminWeisheit** [comment]
Hello Rainer, 

thank you for the explanation. In my case this leads to cyclic dependencies between packages which are actually not there.

So yes, an option to turn the arrow from the implementing class towards the interface would be very helpful to analyse if the dependency inversion between has been violated. 

It would be really great, if you could implement such a feature.

Best regards,
Ben

**Comment by RainerWinkler** [comment]
Hi Benjamin,

please open a new issue in the SAP2Moose repository for such a feature. I will quite likely implement it then.

Best regards,
Rainer

**Comment by BenjaminWeisheit** [comment]
Hello Rainer, 

I opened Issue 131 in the SAP2Moose repository.

Thank you,
Ben
